// ReactJS/lcotodo/src/App.js
import React from "react";
import logo from "./logo.svg";
import "./App.css";

class App extends React.Component
{
  constructor(props)
  {
    super(props);
    this.state={
      newItem:"",
      list:[],
    }
  }

  additem(todoValue)
  {
    if(todoValue !=="")
    {
      const newItem={
        id:Date.now(),
        value:todoValue,
        isDone:false
      };
      const list=[...this.state.list];
      list.push(newItem);
      
      this.setState({
        list,
        newItem:""
      });
    }
  }

  deleteitem(id)
  {
    const list=[...this.state.list];
    const updatedlist=list.filter(item=>item.id!==id);
    this.setState({list:updatedlist})
  }

  updateInput(input)
  {
    this.setState({newItem:input});
  }
  render(){
    return(
      <div>
        <img src={logo} width="100" className="logo"/>
        <h1 className="app-title">MY To-Do</h1>
        <div className="container">
          Add an item...<br/>
          <input type="text" className="input-text" 
          placeholder="Write a to-do" 
          required 
          value={this.state.newItem} 
          onChange={e => this.updateInput(e.target.value)}
          />
          <button className="add-btn" 
          onClick={() => this.additem(this.state.newItem)}
          disabled={!this.state.newItem.length}
          >Add to do</button>
          <div className="list">
            <ul>
              {this.state.list.map(item => {
                return(
                  <li key={item.id}>
                    <input type="checkbox" name="isDone"
                    checked={item.isDone}
                    onChange={()=> {}}
                    />
                    {item.value}
                    <button className="btn" onClick={() =>this.deleteitem(item.id)}>Delete</button>
                  </li>
                )
              })}
              <li><input type="checkbox" />Record Videoz
              <button className="btn">Delete</button></li>
            </ul>
          </div>
        </div>
      </div>
    )
  }
}

export default App;

// Angular/project/src/app/app.component.ts
import { Todo } from './todo';
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent 
{
  title = 'Project';
  todoValue:string;
  list: Todo[];
  ngOnInit()
  {
    this.list=[];
    this.todoValue="";
  }
  addItem()
  {
    if(this.todoValue !=="")
    {
      const newItem: Todo =
      {
        id:Date.now(),
        value:this.todoValue,
        isDone:false
      };
      this.list.push(newItem);
    }
    this.todoValue="";
  }
  deleteItem(id: number)
  {
    this.list=this.list.filter(item => item.id !== id);
  }
}

<div style="text-align: center">
  <img src="../assets/LOGO.png" alt="LCO LOGO" width="100" height="100" class="logo"/>
  <h1 class="app-title">LCO Todo List</h1>
</div>
<div class="container">
  Add a todo..<br>
  <input 
  type="text" 
  class="input-text" 
  placeholder="Type a todo" 
  [(ngModel)]="todoValue"
  (keyup.enter)="addItem()"
  />
  <button class="add-btn" (click)="addItem()">Add Todo</button>
  <div class="list">
    <ul>
      <li *ngFor="let item of list">
        <input type="checkbox" name="isDone"
        [(ngModel)]="item.isDone"
        />
        {{item.value}}
        <button class="btn" (click)="deleteItem(item.id)">Delete</button>
      </li>
    </ul>
  </div>
</div>
